import type { Metadata } from 'next';

import { Footer } from '@/src/widgets/navigation/footer/footer';
import { Header } from '@/src/widgets/navigation/header';
import './globals.css';
import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="layout">
            <header className="headerWrapper">
              <div className="container">
                <Header />
              </div>
            </header>

            <main className="main">
              <div className="container">{children}</div>
            </main>

            <div className="footer-wrapper">
              <div className="container">
                <Footer />
              </div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
