import type { Metadata } from 'next';

import { Header } from '@/src/widgets/navigation/header';
import './globals.css';
import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="layout">
          <header className="headerWrapper">
            <div className="container">
              <Header />
            </div>
          </header>

          <main className="main">
            <div className="container">
              <Providers>{children}</Providers>
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
